# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            VinnytsiaTeam
tagline:          Learning together.
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Yuriy Grigortsevich
  url:
  email:          GrigortsevichYuriy@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

pages_list:
  Archive: '/archive'
  About: '/about'

#  Feed: '/atom.xml'
