# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            VINTeam
tagline:          Вчимося разом.
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Yuriy Grigortsevich
  url:
  email:          GrigortsevichYuriy@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

pages_list:
  Архів: '/archive'
  Про нас: '/about'

#  Feed: '/atom.xml'
