# Permalinks
permalink:        pretty

# Setup
title:            VinnytsiaTeam
tagline:          Вчимося разом.
url:              http://getpoole.com
paginate:         1
baseurl:          ""
author:
  name:           Yuriy Grigortsevich
  url:
  email:          GrigortsevichYuriy@gmail.com

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Custom vars
version:          2.0.0
github:
  repo:           https://github.com/poole/poole

pages_list:
  Архів: '/archive'
  Про нас: '/about'

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
